* Featherweight Emacs in a Docker

WARNING: This package is not stable yet. I might change the base or break this at any time ~:)~

A super lightweight emacs in your docker

The contemporary version of this package is [[https://github.com/Silex/docker-emacs][Silex/docker-emacs]].

* Usage

Get it at [[https://hub.docker.com/r/jgkamat/emacs/][jgkamat/emacs]]!

#+BEGIN_SRC shell
  docker run -ti jgkamat/emacs:25.2 emacs
#+END_SRC

I'll try to support as many versions of emacs as alpine will, submit a PR if you find anything lacking.

** Available Tags
- ~jgkamat/emacs:25.1~
- ~jgkamat/emacs:25.2~

* Why?

I use Emacs for many things, not just for editing text! For example, I generate
almost 100% of my written content in the fantastic [[http://orgmode.org/][org-mode]]. I need docker
images of emacs to run these, for quick and reproducible builds.

While Silex/docker-emacs is probably the best environment to get started on, it
is lacking quite a bit for my use case.

1. It's huge, weighing in at almost 900mb.
2. It contains all of Emacs build dependencies, which are generally unneeded at
   run time.
3. It is self-compiled, which can lead to missing features (making sure
   everything is properly compiled is a pain)
4. Suffers from [[https://github.com/moby/moby/issues/22801]]
5. It is not an automated build (leading to trust issues).

While Silex/docker-emacs is useful if you want to test on specific emacs
versions (since it compiles it's own version it can achieve this), this is not
100% necessary for many usecases.

* Overview

jgkamat/airy-docker-emacs is:

1. Built from alpine/alpine, so it's as small as possible
2. Built using Emacs packages provided from alpine, so they are properly tested
   and maintained
3. Builds in seconds, rather than minutes
4. An automated build
5. Easily buildable on any machine.
6. Dead simple (take a look at the dockerfiles).

jgkamat/airy-docker-emacs is NOT:

1. Able to provide specific Emacs versions older than 25.1 (the oldest version
   packaged by alpine).

* Size Comparison

| Repo                           | Size  |
|--------------------------------+-------|
| Silex/docker-emacs:25          | 856MB |
| jgkamat/airy-docker-emacs:25.2 | 160MB |

* Build Time

(I understand this is not a fair comparison, but I can't build these on my
laptop to find out anyway)

| Repo                                    | Time       |
|-----------------------------------------+------------|
| Silex/docker-emacs:25 (travis)          | 16 minutes |
| jgkamat/airy-docker-emacs:25.2 (laptop) | 20s        |

* Personal Dotfile Build Time

Results are from emacs byte compilation of my dotfiles and their dependencies in
circleci

| Repo                           | Build Time | Source    |
|--------------------------------+------------+-----------|
| Silex/docker-emacs:25          |       1:20 | [[https://circleci.com/gh/jgkamat/dotfiles/262][build 262]] |
| jgkamat/airy-docker-emacs:25.2 |       0:56 | [[https://circleci.com/gh/jgkamat/dotfiles/304][build 304]] |
