from alpine:3.10

run apk update && apk add \
	git \
	curl \
	python \
	emacs \
	openssh \
	bash \
	git

run curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
env PATH="/root/.cask/bin:${PATH}"
